### ISSUE TITLE
Request to join community 

### ISSUE THREAD

**Issue by feliciarenee00** [biocodellc/localcontexts_ui#10]
Date and Time: April 12, 2021, around 5:45 pm MDT

Browser: Chrome, Version 89.0.4389.72 (Official Build) (x86_64)

Error code: n/a

Page with error: /communities/community-registry/

Details: If you select to join a community that already exists, after you select “Send request to join,” button should change to “Sent.” Also, once the request is sent, you are still able to click on the "Send request to join" button and send requests multiple times right now, which will all show up on the admin's requests page.

**Comment by birbjam** [comment]
Done!
