### ISSUE TITLE
Customizing a label for a project 

### ISSUE THREAD

**Issue by feliciarenee00** [biocodellc/localcontexts_ui#11]
Date and Time: March 25, 2021, around 4pm MDT

Browser: Chrome, Version 89.0.4389.72 (Official Build) (x86_64)

Error code: n/a

Page with error: /communities/community/labels/customise/tk/10/tknc

Details: When you click on the tab to create a project and try to add a label, it opens a new window to begin customizing. Once you are done customizing, there is not a “send for approval” button (currently “save as draft”). However, when you return to the project page, the project draft is not saved. Maybe this needs some more text to inform the user of the approval process? Will the project draft re-appear once the label is approved?

**Comment by birbjam** [comment]
This issue has been discussed with Maui and Jane. The functionality will be changed to first creating/saving a project and then being able to apply labels to it separately.

**Comment by feliciarenee00** [comment]
Great, thank you!
