### ISSUE TITLE
500 internal server error when creating community 

### ISSUE THREAD

**Issue by feliciarenee00** [biocodellc/localcontexts_ui#14]
<img width="1481" alt="Screen Shot 2021-04-18 at 1 19 44 PM" src="https://user-images.githubusercontent.com/81319946/115157984-33f9d580-a049-11eb-9011-a482ebbcec87.png">

**Date and Time:** April 18, 2021, 1:18 pm MDT

**Browser:** Chrome, Version 89.0.4389.72 (Official Build) (x86_64)

**Error code:** 500

**Page with error:** /communities/create-community/

**Details:** I was creating a new community and when I clicked continue, I encountered this error code. I wonder if it was because I used a number in my community name (Test Community 3). When I re-submit with no numeric values, I was able to create the community. 

**See attached screenshot.**

**Comment by birbjam** [comment]
This should be fixed now.
