### ISSUE TITLE
500 error when applying Labels

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#18]
**Date and Time:** May 23, 1:05 pm ET

**Which browser & version are you using?** Chrome, 90.0.4430.212

**What was the error code?** 500 internal server error

**Which page had the error and what were you doing when it happened? Be as detailed as possible.**
In a community account, attempting to apply Labels to a project. (url: https://anth-ja77-local-contexts-8985.uc.r.appspot.com/communities/community/activity/notice/add/21/e1597cdb-aacb-4605-b15e-02ba89a256ae) 

Tried to apply two TK Labels, Multiple Communities (TK MC) & Verified (TK V), to project “Globalized Conflicts…” from Petra B. in the Northeast Nation community account. This resulted in the 500 error. I used back button, was brought back to Label selection, and got the same same error when attempting to apply just TK MC.

I used the back button again and attempted to apply just TK V. This worked, but it seems to have applied TK V and TK MC when looking at the project on the Project tab.

**Screenshot or screen recording if possible.** n/a

**Comment by birbjam** [comment]
Email related to this error:

> Internal Server Error: /communities/community/activity/notice/add/21/e1597cdb-aacb-4605-b15e-02ba89a256ae
> 
> DataError at /communities/community/activity/notice/add/21/e1597cdb-aacb-4605-b15e-02ba89a256ae
> value too long for type character varying(200)

**Comment by birbjam** [comment]
This had to do with long project titles being added to instances of ActionNotification where the character limit for the notification title was 200 characters. Shortened all created project titles to 30 characters for notifications so it should be working now.
