### ISSUE TITLE
Project Notice sent to 2 communities — message

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#19]
**Date and Time:** May 31. 2021 12:30 pm ET (replicated issue found during testing, May 30, ~5:30 pm ET)
**Which browser & version are you using?** Chrome, 90.0.4430.212 (tester was using Edge)
**What was the error code?** n/a
**Which page had the error and what were you doing when it happened? Be as detailed as possible.**
In an institution account, using the Notify button to send a Project / Notice to a community. If the project is sent to community 1 with message 1, then the project is sent to community 2 with message 2 > message 1 will be replaced by message 2 for community 1. This is if the Notify button is used two separate times to notify communities one at a time. I replicated this with the Natural History Museum sending Test project 3 to Community of the Southwest and then Northeast Nation, which is illustrated in the screen recording. The tester from May 30 sent their project to Te Kahui Maru with one message and then sent to Northeast Nation and their Te Kahui Maru message was replaced by the message to Northeast Nation.
[Screen recording.](https://drive.google.com/file/d/10FZW0dHy3t603ZVcm9MKm2NR1LyOlKzZ/view?usp=sharing)

**Comment by birbjam** [comment]
This has been fixed in development, will update the beta site before this weekend. Good catch as always!
