### ISSUE TITLE
500 internal server error when creating community 

### ISSUE THREAD

**Issue by feliciarenee00** [biocodellc/localcontexts_ui#3]
I was creating a new community (around 3:30pm MDT) and when I entered the community name it brought me to a 500 internal server error at /communities/create-community/ I suspect this is because I entered "Test Community" for the name, but that community already existed.

**Comment by birbjam** [comment]
TODO: add error messages to `create-community` page and check for duplicate community names before creating a community.

**Comment by birbjam** [comment]
Fixed
