### ISSUE TITLE
Institution dashboard tabs do not indicate which page you are on

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#5]
**Date and Time:** April 4, 2021, 1:12 pm ET

**Browser:** Chrome, Version 89.0.4389.114 (Official Build) (x86_64)

**Error code:** n/a

**Page with error:** /institutions/institution/1/

**Details:**  On the institution dashboard, the tabs do not have a visual indicator to show which page you are on, i.e. Activity, Notices, Projects, Requests. You can click on any of these pages titles, but the text stays gray. [See screen recording.](https://drive.google.com/file/d/1Kj2RSx0DS_hfSLB0nd64miv8ClsSHieH/view?usp=sharing)

**Comment by birbjam** [comment]
Updated
