### ISSUE TITLE
Project orcid opens in same window

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#7]
**Date and Time** April 8, 2021 7:55 pm ET
**Which browser & version are you using?** Chrome Version 89.0.4389.114 (Official Build) (x86_64)
**What was the error code?** n/a
**Which page had the error and what were you doing when it happened? Be as detailed as possible.** The project tab on a researcher account. Clicking the "View Orcid" button after a project has been saved opens the Orcid page in the same window — can this be opened in a new window?
**Screenshot or screen recording if possible.** [Find recording here.](https://drive.google.com/file/d/1Vw-xb08K3W_3mT9eiHQveRwqw-f5guT5/view?usp=sharing)

**Comment by birbjam** [comment]
Updated.
